version: 1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: Result.OrDefault.sln

after_test:
  - ps: .\.nuget\pack.ps1

artifacts:
  - path: Result.OrDefault\bin\Release\Result.OrDefault.dll
    name: Result.OrDefault.dll
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: mYNxybjJqKR3bOn+cYo6o7SPvlgOApzwnI7rep4TCYjTjYgb7T1fG28lFrgcX2Jk
  artifact: /.*\.nupkg/
  